<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
<!ELEMENT root (residence+)>
<!ELEMENT residence (infos, address?, house_services)>
<!ELEMENT infos (bus?, tramway?, loyer)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT house_services (house_service+)>
<!ELEMENT bus (arret+)>
<!ELEMENT tramway (arret+)>
<!ELEMENT loyer ((t1b|t2|t3)+)>
<!ELEMENT arret (ligne+)>
<!ELEMENT t1b (#PCDATA)>
<!ELEMENT t2 (#PCDATA)>
<!ELEMENT t3 (#PCDATA)>
<!ELEMENT ligne (#PCDATA)>
<!ELEMENT house_service (#PCDATA)>
<!ATTLIST residence id CDATA #REQUIRED>
<!ATTLIST residence title CDATA #REQUIRED>
<!ATTLIST residence short_desc CDATA #IMPLIED>
<!ATTLIST residence lat CDATA #IMPLIED>
<!ATTLIST residence lon CDATA #IMPLIED>
<!ATTLIST residence zone CDATA #IMPLIED>
<!ATTLIST arret nom CDATA #REQUIRED>
<!ATTLIST t1b superficie CDATA #REQUIRED>
<!ATTLIST t1b nombre CDATA #IMPLIED>
<!ATTLIST t2 superficie CDATA #REQUIRED>
<!ATTLIST t2 nombre CDATA #IMPLIED>
<!ATTLIST t3 superficie CDATA #REQUIRED>
<!ATTLIST t3 nombre CDATA #IMPLIED>
]>
<root>
	<residence id="961" title="Cité U' Launay Violette" lat="47.2493057251" lon="-1.5588680506" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Bourgeonnière">
					<ligne>26</ligne>
					<ligne>86</ligne>
				</arret>
				<arret nom="Recteur-Schmitt">
					<ligne>26</ligne>
					<ligne>75</ligne>
					<ligne>80</ligne>
					<ligne>86</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Bourgeoniere">
					<ligne>2</ligne>
				</arret>
				<arret nom="Recteur-Schmitt">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
			</loyer>
		</infos>
		<address>Chemin de Launay Violette, 44322 Nantes</address>
		<house_services>
			<house_service>Parking</house_service>
			<house_service>Cuisine collective</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Laverie</house_service>
			<house_service>Salle de détente</house_service>
			<house_service>Salle informatique</house_service>
			<house_service>Salle de travail</house_service>
			<house_service>Salle TV</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Studio de musique</house_service>
		</house_services>
	</residence>
	<residence id="962" title="Cité U' La Bourgeonnière" lat="47.2536315918" lon="-1.5635741949" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Bourgeonnière">
					<ligne>26</ligne>
					<ligne>86</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Bourgeoniere">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
			</loyer>
		</infos>
		<house_services>
			<house_service>Cuisine collective</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Salle de détente</house_service>
			<house_service>Salle informatique</house_service>
			<house_service>Salle de travail</house_service>
			<house_service>Salle TV</house_service>
			<house_service>Salle de sport</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Bibliothèque</house_service>
		</house_services>
	</residence>
	<residence id="963" title="Cité U' Fresche Blanc" lat="47.2513237" lon="-1.5567330122" zone="NANTES">
		<infos>
			<tramway>
				<arret nom="Recteur-Schmitt">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Logement adaptable</house_service>
			<house_service>Parking PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Salle de détente</house_service>
			<house_service>Salle de travail</house_service>
			<house_service>Salle TV</house_service>
			<house_service>Surveillance / Sécurité</house_service>
		</house_services>
	</residence>
	<residence id="964" title="Cité U' Berlioz" lat="47.2379226685" lon="-1.5773129463" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Diane">
					<ligne>12</ligne>
				</arret>
				<arret nom="Berlioz">
					<ligne>C2</ligne>
				</arret>
				<arret nom="Grootaers">
					<ligne>C20</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Longchamp">
					<ligne>3</ligne>
				</arret>
			</tramway>
			<loyer>
			</loyer>
		</infos>
		<house_services>
			<house_service>Parking</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Salle de travail</house_service>
			<house_service>Salle TV</house_service>
			<house_service>Salle de sport</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Distribution protections périodiques</house_service>
			<house_service>Distributeur boissons confiseries</house_service>
		</house_services>
	</residence>
	<residence id="965" title="Cité U' Casterneau" lat="47.2285079956" lon="-1.5296529531" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Mitrie">
					<ligne>10</ligne>
					<ligne>11</ligne>
					<ligne>12</ligne>
				</arret>
				<arret nom="Bd de Doulon">
					<ligne>C3</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Bd de Doulon">
					<ligne>1</ligne>
				</arret>
			</tramway>
			<loyer>
			</loyer>
		</infos>
		<house_services>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Salle de détente</house_service>
			<house_service>Salle informatique</house_service>
			<house_service>Salle de travail</house_service>
			<house_service>Surveillance / Sécurité</house_service>
		</house_services>
	</residence>
	<residence id="966" title="Cité U' Chanzy" lat="47.2259407043" lon="-1.5474090576" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Cambronne">
					<ligne>C6</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="St-Mihiel">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Cuisine collective</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Salle de détente</house_service>
			<house_service>Salle informatique</house_service>
			<house_service>Salle de travail</house_service>
			<house_service>Salle TV</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Distribution protections périodiques</house_service>
			<house_service>Distributeur boissons confiseries</house_service>
		</house_services>
	</residence>
	<residence id="967" title="Résidence de la réussite Wangari Maathaï" lat="47.2504196167" lon="-1.5598549843" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Vincent Scotto">
					<ligne>86</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Bourgeoniere">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
				<t2 superficie="39" nombre="54"></t2>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Parking PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
		</house_services>
	</residence>
	<residence id="968" title="Résidence U' Les Landes" lat="47.2527694702" lon="-1.5613030195" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Bourgeoniere">
					<ligne>86</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Bourgeoniere">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
				<t1b superficie="31" nombre="31"></t1b>
				<t2 superficie="43" nombre="2"></t2>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Parking PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
		</house_services>
	</residence>
	<residence id="969" title="Résidence U' Alice Milliat" lat="47.2491188049" lon="-1.5542190075" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Ecole centrale">
					<ligne>20</ligne>
					<ligne>26</ligne>
					<ligne>75</ligne>
					<ligne>80</ligne>
					<ligne>66</ligne>
					<ligne>E5</ligne>
				</arret>
				<arret nom="Guy mollet">
					<ligne>20</ligne>
					<ligne>26</ligne>
					<ligne>75</ligne>
					<ligne>80</ligne>
					<ligne>66</ligne>
					<ligne>E5</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Ecole centrale - audencia">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
				<t1b superficie="32" nombre="6"></t1b>
			</loyer>
		</infos>
		<house_services>
			<house_service>Ascenseur</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
		</house_services>
	</residence>
	<residence id="970" title="Résidence U' Les Saumonières" lat="47.2551040649" lon="-1.5516899824" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Rivière">
					<ligne>C5</ligne>
					<ligne>75</ligne>
					<ligne>50</ligne>
					<ligne>66</ligne>
					<ligne>80</ligne>
					<ligne>86</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Recteur-Schmitt">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
			</loyer>
		</infos>
		<house_services>
			<house_service>Parking</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
		</house_services>
	</residence>
	<residence id="971" title="Résidence U' Olympe de Gouges" lat="47.2527351379" lon="-1.5562850237" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Bourgeoniere">
					<ligne>86</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Bourgeoniere">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
				<t1b superficie="18" nombre="214"></t1b>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Parking PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Surveillance / Sécurité</house_service>
		</house_services>
	</residence>
	<residence id="972" title="Résidence U 'Jacques Tymen" lat="47.2547264099" lon="-1.5460430384" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Rivière">
					<ligne>E5</ligne>
					<ligne>75</ligne>
					<ligne>50</ligne>
					<ligne>66</ligne>
					<ligne>80</ligne>
					<ligne>86</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Recteur-Schmitt">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
				<t1b superficie="30" nombre="26"></t1b>
			</loyer>
		</infos>
		<house_services>
			<house_service>Parking</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
		</house_services>
	</residence>
	<residence id="973" title="Résidence U' Corbilo" lat="47.2025222778" lon="-1.5433219671" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Mangin">
					<ligne>26</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Mangin">
					<ligne>2</ligne>
					<ligne>3</ligne>
				</arret>
			</tramway>
			<loyer>
				<t1b superficie="30" nombre="27"></t1b>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Parking PMR</house_service>
			<house_service>Ascenseur</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Distribution protections périodiques</house_service>
			<house_service>Kitchenette individuelle</house_service>
		</house_services>
	</residence>
	<residence id="974" title="Résidence U' Ile de Nantes" lat="47.2048683167" lon="-1.5581860542" zone="NANTES">
		<infos>
			<bus>
				<arret nom="République">
					<ligne>C5</ligne>
					<ligne>26</ligne>
				</arret>
			</bus>
			<loyer>
				<t2 superficie="27" nombre="9"></t2>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Ascenseur</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Distribution protections périodiques</house_service>
			<house_service>Kitchenette individuelle</house_service>
		</house_services>
	</residence>
	<residence id="975" title="Résidence U' Longchamp" lat="47.2384872437" lon="-1.5774370432" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Diane">
					<ligne>12</ligne>
				</arret>
				<arret nom="Berlioz">
					<ligne>C2</ligne>
				</arret>
				<arret nom="Grootaers">
					<ligne>C20</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Longchamp">
					<ligne>3</ligne>
				</arret>
			</tramway>
			<loyer>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Parking PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Distribution protections périodiques</house_service>
			<house_service>Kitchenette individuelle</house_service>
		</house_services>
	</residence>
	<residence id="976" title="Résidence U' Jean Tusques" lat="47.2270698547" lon="-1.5195749998" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Toutes aides">
					<ligne>10</ligne>
					<ligne>12</ligne>
					<ligne>87</ligne>
				</arret>
				<arret nom="Mairie de Doulon">
					<ligne>12</ligne>
					<ligne>87</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Mairie de Doulon">
					<ligne>1</ligne>
				</arret>
			</tramway>
			<loyer>
				<t1b superficie="31" nombre="15"></t1b>
				<t2 superficie="51" nombre="4"></t2>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Kitchenette individuelle</house_service>
		</house_services>
	</residence>
	<residence id="977" title="Résidence U' Léonard de Vinci" lat="47.2297821045" lon="-1.5444732904" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Chpalet">
					<ligne>C6</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Motte Rouge">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
				<t1b superficie="30" nombre="4"></t1b>
				<t2 superficie="45" nombre="2"></t2>
			</loyer>
		</infos>
		<house_services>
			<house_service>Parking</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Kitchenette individuelle</house_service>
		</house_services>
	</residence>
	<residence id="978" title="Résidence U' La Haute Forêt" lat="47.232875824" lon="-1.5550800562" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Haute Forêt">
					<ligne>23</ligne>
					<ligne>10</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Saint Felix">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
				<t1b superficie="28" nombre="11"></t1b>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Parking PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Laverie</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Kitchenette individuelle</house_service>
		</house_services>
	</residence>
	<residence id="979" title="Résidence U' Madeleine Brès" lat="47.2660102844" lon="-1.5647039413" zone="NANTES">
		<infos>
			<bus>
				<arret nom="Géraudière">
					<ligne>50</ligne>
					<ligne>96</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Chêne des Anglais">
					<ligne>2</ligne>
				</arret>
				<arret nom="Santos Dumont">
					<ligne>2</ligne>
				</arret>
			</tramway>
			<loyer>
				<t3 superficie="36" nombre="44"></t3>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Logement adaptable</house_service>
			<house_service>Parking PMR</house_service>
			<house_service>Parking</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Kitchenette individuelle</house_service>
		</house_services>
	</residence>
	<residence id="1272" title="Résidence U' O Slow" lat="47.202863" lon="-1.553203" zone="NANTES">
		<infos>
			<bus>
				<arret nom="MIN">
					<ligne>26</ligne>
					<ligne>C5</ligne>
				</arret>
			</bus>
			<tramway>
				<arret nom="Vincent Gâche">
					<ligne>2</ligne>
					<ligne>3</ligne>
				</arret>
			</tramway>
			<loyer>
				<t2 superficie="35" nombre="16"></t2>
			</loyer>
		</infos>
		<house_services>
			<house_service>Accessible PMR</house_service>
			<house_service>Ascenseur</house_service>
			<house_service>Douche individuelle</house_service>
			<house_service>Garage à vélos</house_service>
			<house_service>Internet / Wifi</house_service>
			<house_service>Salle de détente</house_service>
			<house_service>Salle de sport</house_service>
			<house_service>Surveillance / Sécurité</house_service>
			<house_service>Kitchenette individuelle</house_service>
		</house_services>
	</residence>
</root>
